### ISSUE TITLE
160 basic example I2C address, IRQ

### ISSUE THREAD

**Issue by starbrights** [sciosense/ens16x-arduino#3]
Thanks for providing lib and example.
Have some problems get the basic 160 example running.
First I have to change I2C address from 0x52 to 0x53, than init works.
(Maybe that is worth to mention in example:
The I2C slave address is 0x52 (MISO/ADDR low) or 0x53 (MISO/ADDR high))

The wires in your example doesn't include an INT line - shouldn't be USE_INTERRUPT undefined?

I added a line
ens160.writeCompensation(temperature, relativeHumidity);
just to be sure. But ok, that might be optional.

ens160.update() give me just once an OK!?! and hence return only one time this:
QI UBA: 0 RS0: 1	RS1: 1	RS2: 1	RS3: 1
I need to uncomment ens160.getTvoc() and ens160.getEco2() as it crashes the system ?!?

Can you help me debug that?
The board is a combined one with AHT20 and ENS160 and runs on EP8266 D1 Mini

14:20:08.820 -> ENS160 debug -- reset status: ok
14:20:08.852 -> ENS160 debug -- PART_ID  :  0x160
14:20:08.852 -> Firmware: 5.4.6

--
After reading the manual I found in section 10.1 Initial Start-up and 10.2 Warm-up.  I don't see this is triggered in example.

**Comment by starbrights** [comment]
Readin in the previous github issues it might be that voltage drop is the issue. 
I found it difficult to solder some capacitor close to sensor. Will a capacitor at the 5V input of the bord help as well?

**Comment by TRScioSense** [comment]
Please make sure you're following the [datasheet ](https://www.sciosense.com/wp-content/uploads/2023/12/ENS160-Datasheet.pdf)recommendations. Fig 14 describes the wiring including interrupt pins. Furthermore make sure your electrical parameters stay withing the limits (table 2+3) and add a capacitor of 10µF close to VDD of the sensor (not on 3.3V input).
Within the code make sure the line 12 and 13 are uncommented and the pin is accordingly assigned to your wiring
```
#define USE_INTERRUPT
#define INTN 2
```
Besides our supported library, you can implement your own functions by reading the registers as basic I²C communication
